on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.13'
    - run: go test ./...
